// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Hello: typeof import('./src/components/hello.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
    Swiper: typeof import('./src/components/swiper.vue')['default']
  }
}
