/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ClassLogin: typeof import('./src/components/classLogin.vue')['default']
    Listitem: typeof import('./src/components/listitem.vue')['default']
    Notify: typeof import('./src/components/notify.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCard: typeof import('@nutui/nutui-taro')['Card']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutCheckboxGroup: typeof import('@nutui/nutui-taro')['CheckboxGroup']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutCollapse: typeof import('@nutui/nutui-taro')['Collapse']
    NutCollapseItem: typeof import('@nutui/nutui-taro')['CollapseItem']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNotify: typeof import('@nutui/nutui-taro')['Notify']
    NutPagination: typeof import('@nutui/nutui-taro')['Pagination']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutPrice: typeof import('@nutui/nutui-taro')['Price']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTable: typeof import('@nutui/nutui-taro')['Table']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    NutUploader: typeof import('@nutui/nutui-taro')['Uploader']
  }
}
